apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-host
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: php-host
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: php-host
    spec:
      containers:
      - name: php-host
        image: zveselinov/php-host:%IMAGE-PLACEHOLDER%
        ports:
        - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: php-host
  labels:
    app: php-host
spec:
  type: NodePort
  ports:
  - port: 9000
    nodePort: 32000
    protocol: TCP
  selector:
    app: php-host
    
   
